### ISSUE TITLE
Module continuously does corrective changes to configured bindings.

### ISSUE THREAD

**Issue by aaronhilton0** [puppetlabs/puppetlabs-iis#346] opened 2022-08-03 19:50 UTC
## Describe the Bug
The puppetlabs-iis module is continuously doing corrective changes to binding configurations within the manifests. I am able to duplicate the problem with some of the example code on the forge modules page. Examples of code and output are below.

## Expected Behavior
The module should set the binding configurations once and only make changes when corrections are actually needed

## Steps to Reproduce
I was able to reproduce with the following Puppet code
```
# using example in forge
class profile::iis_site2 {

# Create Directories

file { 'c:\\inetpub\\complete':
  ensure => 'directory'
}

file { 'c:\\inetpub\\complete_vdir':
  ensure => 'directory'
}

# Set Permissions

acl { 'c:\\inetpub\\complete':
  permissions => [
    {'identity' => 'IIS_IUSRS', 'rights' => ['read', 'execute']},
  ],
}

acl { 'c:\\inetpub\\complete_vdir':
  permissions => [
    {'identity' => 'IIS_IUSRS', 'rights' => ['read', 'execute']},
  ],
}

# Configure IIS

iis_application_pool { 'complete_site_app_pool':
  ensure                  => 'present',
  state                   => 'started',
  managed_pipeline_mode   => 'Integrated',
  managed_runtime_version => 'v4.0',
}

# Application Pool No Managed Code .Net CLR Version set up
iis_application_pool {'test_app_pool':
    ensure                    => 'present',
    enable32_bit_app_on_win64 => true,
    managed_runtime_version   => '',
    managed_pipeline_mode     => 'Classic',
    start_mode                => 'AlwaysRunning'
  }

iis_site { 'complete':
  ensure           => 'started',
  physicalpath     => 'c:\\inetpub\\complete',
  applicationpool  => 'complete_site_app_pool',
  enabledprotocols => 'https',
  bindings         => [
    {
      'bindinginformation'   => '*:443:',
      'protocol'             => 'https',
      'certificatehash'      => '3598FAE5ADDB8BA32A061C5579829B359409856F',
      'certificatestorename' => 'MY',
      'sslflags'             => 1,
    },
  ],
  require => File['c:\\inetpub\\complete'],
}

iis_virtual_directory { 'vdir':
  ensure       => 'present',
  sitename     => 'complete',
  physicalpath => 'c:\\inetpub\\complete_vdir',
  require      => File['c:\\inetpub\\complete_vdir'],
}

}
```

This code reports the following corrective changes every time the agent runs.
```
Running Puppet agent on demand ...
Info: Using environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Info: Caching catalog for ah-node2win-a13c00-0.us-west1-c.c.customer-support-scratchpad.internal
Info: Applying configuration version 'ahpepri2019-a13c00-0-production-5fe7e9cc693'
Notice: /Stage[main]/Profile::Iis_site2/Iis_site[complete]/bindings: bindings changed [
  {
    'certificatestorename' => '',
    'protocol' => 'https',
    'sslflags' => 1,
    'certificatehash' => '',
    'bindinginformation' => '*:443:'
  }] to [
  {
    'bindinginformation' => '*:443:',
    'protocol' => 'https',
    'certificatehash' => '3598FAE5ADDB8BA32A061C5579829B359409856F',
    'certificatestorename' => 'MY',
    'sslflags' => 1
  }] (corrective)
Notice: Applied catalog in 7.94 seconds
Press any key to continue . . .
```

## Environment
 - Puppetlabs-iis module version 8.1.0
 - Tested with both puppetlabs-pwshlib v0.6.3 matching customer environment and v0.10.2 (latest)

**Comment by david22swan** [comment] 2022-08-25 14:28
Writing down thoughts.....

- Able to reproduce:
![Screen Shot 2022-08-25 at 3 22 55 PM](https://user-images.githubusercontent.com/21069923/186690982-cfcf2f58-5bc0-4479-b1a6-e15b34711be0.png)

- Running the iis command to retrieve websites, gives the same information:
![Screen Shot 2022-08-25 at 3 21 55 PM](https://user-images.githubusercontent.com/21069923/186691130-ea45681b-c862-4a49-a7bf-8df9e572ccd8.png)

Questions?????

- Is this new behaviour, or has it always worked like this?
- Appears that the change is on the windows side.... Is it a new security change??? A way to keep information more secure????
- Continuing from above, is this actually the correct behaviour??? Is there anything we can do???
- Is the site actually set correctly? Is this issue on the retrieving side or setting side?

**Comment by david22swan** [comment] 2022-08-31 11:16
Think I have found the cause of the issue, ink here: https://stackoverflow.com/questions/59765860/powershells-addsslcertificate-not-working-on-iis-10-non-server-binding

**Comment by david22swan** [comment] 2022-08-31 12:26
Looking deeper into the issue, look's like it may arise from our commands being out of date.
We may need to update the code to use `New-WebBinding` rather than the current `Add-WebConfiguration`.

https://docs.microsoft.com/en-us/powershell/module/webadministration/new-webbinding?view=windowsserver2022-ps

**Comment by david22swan** [comment] 2022-09-01 17:02
Have made some progress:

- Code is cleaned up and updated
- Discovered an issue where if no hostname is set and you try to set ssl_flags it doesn't work, so now if no hostname is given in that situation a default one is used instead, this can cause a corrective change error but is a limitation of iis so not much I can do.
- Still having issues attaching the ssl certification

PR shown here:
https://github.com/puppetlabs/puppetlabs-iis/pull/349/files

**Comment by aaronhilton0** [comment] 2022-09-07 18:53
Customer has tested against commit '125c510' and reports that the certificate hash appears to be correctly populated, however it is still showing as a corrective change. Looking through the attached 
[agentdebug_updated.log](https://github.com/puppetlabs/puppetlabs-iis/files/9508851/agentdebug_updated.log) file, it appears that it is adding 'port' => 80 every run. I've asked the customer to manually add the SSL certificate and will update this issue when I have results.

**Comment by aaronhilton0** [comment] 2022-09-07 18:58
Customer has tested against commit '125c510' and reports that the certificate hash appears to be correctly populated, however it is still showing as a corrective change. Looking through the updated log file, it appears that it is adding 'port' => 80 every run. I've asked the customer to manually add the SSL certificate and will update this issue when I have results.

**Comment by cummingscody** [comment] 2022-09-09 16:48
Customer has reported they can manually assign the cert for binding in IIS and it works.

**Comment by cummingscody** [comment] 2022-09-13 17:21
@david22swan Any further thoughts on this?

**Comment by david22swan** [comment] 2022-09-23 08:15
@cummingscody apologies, had missed the updated saying you'd replied.
Could you show me the exact update message

**Comment by david22swan** [comment] 2022-10-10 08:22
All work now being moved to Jira, here is the associated new ticket: https://tickets.puppetlabs.com/browse/CONT-25

**Comment by pmcmaw** [comment] 2023-01-12 17:01
@cummingscody @aaronhilton0 Just wondering if you are happy with the resolution and can we close this?

**Comment by pmcmaw** [comment] 2023-01-19 15:52
Closing due to no response, if you are still seeing this issue please reopen.

**Closed as completed by pmcmaw** 2023-01-19 15:52 UTC
Labels: bugfix, attention-needed
